import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "@/styles/globals.css"; // 전역 css
import SideNavi from "@/components/common/navi/SideNavi";

const roboto = Roboto({
  // variable: "--font-geist-sans",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Shadcn UI - Todoboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <SideNavi />
        {children}
      </body>
    </html>
  );
}
